project:
  type: website
  output-dir: "docs"

website:
  title: "Jessica Zafra Tanaka"
  navbar:
    left: 
      - text: "Home"
        file: "index.qmd"
      - text: "Portfolio"
        file: "portfolio.qmd"
      - text: "CV"
        file: "cv.qmd"
    right:
      - icon: github
        href: https://github.com/Jzafrat
      - icon: linkedin
        href: https://www.linkedin.com/in/jessica-zafra/
format:
  html:
    theme: superhero
    css: styles.css

editor: visual

